name: Build and Push Docker image

on:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build & Push services
        run: |
          docker-compose -f ./adapter/docker/docker-compose.yml build --no-cache
          COMMIT_SHA=$(git rev-parse --short HEAD)
          docker tag adolphnov/gptworker:latest adolphnov/gptworker:$COMMIT_SHA
          docker push adolphnov/gptworker:latest
          docker push adolphnov/gptworker:$COMMIT_SHA
       
