name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      wrangler-toml:
        description: 'The Wrangler configuration to use'
        required: true
      api-token:
        description: 'The Cloudflare API token'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ inputs.api-token }}
        run: npx wrangler deploy --config ${{ inputs.wrangler-toml }} --env production --no-ansi --no-telemetry

      - name: Check CF_WORKERS_DOMAIN exists
        env:
          CF_WORKERS_DOMAIN: ${{ secrets.CF_WORKERS_DOMAIN }}
        run: |
          url=${{ secrets.CF_WORKERS_DOMAIN }}
          if [ -z "$url" ]; then
            echo "CF_WORKERS_DOMAIL does not exist"
          else
            echo "CF_WORKERS_DOMAIN exists"
            curl -s -o /dev/null https://$url/init
          fi
